# Form implementation generated from reading ui file 'ankimorphs/ui/camel_manager_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CamelManagerDialog(object):
    def setupUi(self, CamelManagerDialog):
        CamelManagerDialog.setObjectName("CamelManagerDialog")
        CamelManagerDialog.resize(500, 400)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CamelManagerDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.camelInstallPushButton = QtWidgets.QPushButton(parent=CamelManagerDialog)
        self.camelInstallPushButton.setObjectName("camelInstallPushButton")
        self.horizontalLayout.addWidget(self.camelInstallPushButton)
        self.camelInstallationStatusLabel = QtWidgets.QLabel(parent=CamelManagerDialog)
        font = QtGui.QFont()
        font.setItalic(True)
        self.camelInstallationStatusLabel.setFont(font)
        self.camelInstallationStatusLabel.setObjectName("camelInstallationStatusLabel")
        self.horizontalLayout.addWidget(self.camelInstallationStatusLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.databasesListWidget = QtWidgets.QListWidget(parent=CamelManagerDialog)
        self.databasesListWidget.setObjectName("databasesListWidget")
        self.horizontalLayout_2.addWidget(self.databasesListWidget)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.installDatabasePushButton = QtWidgets.QPushButton(parent=CamelManagerDialog)
        self.installDatabasePushButton.setObjectName("installDatabasePushButton")
        self.verticalLayout_3.addWidget(self.installDatabasePushButton)
        self.deleteDatabasePushButton = QtWidgets.QPushButton(parent=CamelManagerDialog)
        self.deleteDatabasePushButton.setObjectName("deleteDatabasePushButton")
        self.verticalLayout_3.addWidget(self.deleteDatabasePushButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.purgeCamelPushButton = QtWidgets.QPushButton(parent=CamelManagerDialog)
        self.purgeCamelPushButton.setObjectName("purgeCamelPushButton")
        self.verticalLayout_3.addWidget(self.purgeCamelPushButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(CamelManagerDialog)
        QtCore.QMetaObject.connectSlotsByName(CamelManagerDialog)

    def retranslateUi(self, CamelManagerDialog):
        _translate = QtCore.QCoreApplication.translate
        CamelManagerDialog.setWindowTitle(_translate("CamelManagerDialog", "CAMeL Tools Manager"))
        self.camelInstallPushButton.setText(_translate("CamelManagerDialog", "Install CAMeL Tools"))
        self.camelInstallationStatusLabel.setText(_translate("CamelManagerDialog", "CAMeL Tools is not installed. Please install it to continue."))
        self.installDatabasePushButton.setText(_translate("CamelManagerDialog", "Install Database"))
        self.deleteDatabasePushButton.setText(_translate("CamelManagerDialog", "Delete Database"))
        self.purgeCamelPushButton.setText(_translate("CamelManagerDialog", "Purge CAMeL Tools"))
