# Form implementation generated from reading ui file 'ankimorphs/ui/frequency_file_generator.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FrequencyFileGeneratorDialog:
    def setupUi(self, FrequencyFileGeneratorDialog):
        FrequencyFileGeneratorDialog.setObjectName("FrequencyFileGeneratorDialog")
        FrequencyFileGeneratorDialog.resize(424, 166)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(FrequencyFileGeneratorDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputButton = QtWidgets.QPushButton(parent=FrequencyFileGeneratorDialog)
        self.inputButton.setObjectName("inputButton")
        self.verticalLayout.addWidget(self.inputButton)
        self.outputButton = QtWidgets.QPushButton(parent=FrequencyFileGeneratorDialog)
        self.outputButton.setObjectName("outputButton")
        self.verticalLayout.addWidget(self.outputButton)
        self.label = QtWidgets.QLabel(parent=FrequencyFileGeneratorDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=FrequencyFileGeneratorDialog)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=FrequencyFileGeneratorDialog)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.comboBox = QtWidgets.QComboBox(parent=FrequencyFileGeneratorDialog)
        self.comboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_2.addWidget(self.comboBox, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.createFrequencyFileButton = QtWidgets.QPushButton(parent=FrequencyFileGeneratorDialog)
        self.createFrequencyFileButton.setStyleSheet("margin-top: 10px;\n"
"margin-bottom: 10px;\n"
"padding: 5px;")
        self.createFrequencyFileButton.setObjectName("createFrequencyFileButton")
        self.verticalLayout_3.addWidget(self.createFrequencyFileButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(FrequencyFileGeneratorDialog)
        QtCore.QMetaObject.connectSlotsByName(FrequencyFileGeneratorDialog)

    def retranslateUi(self, FrequencyFileGeneratorDialog):
        _translate = QtCore.QCoreApplication.translate
        FrequencyFileGeneratorDialog.setWindowTitle(_translate("FrequencyFileGeneratorDialog", "Frequency File Generator"))
        self.inputButton.setText(_translate("FrequencyFileGeneratorDialog", "Select input"))
        self.outputButton.setText(_translate("FrequencyFileGeneratorDialog", "Select output"))
        self.label.setText(_translate("FrequencyFileGeneratorDialog", "Morphemizer:"))
        self.createFrequencyFileButton.setText(_translate("FrequencyFileGeneratorDialog", "Create Frequency File"))
