# Form implementation generated from reading ui file 'ankimorphs/ui/known_morphs_exporter.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_KnownMorphsExporterDialog(object):
    def setupUi(self, KnownMorphsExporterDialog):
        KnownMorphsExporterDialog.setObjectName("KnownMorphsExporterDialog")
        KnownMorphsExporterDialog.resize(430, 145)
        self.verticalLayout = QtWidgets.QVBoxLayout(KnownMorphsExporterDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectOutputPushButton = QtWidgets.QPushButton(parent=KnownMorphsExporterDialog)
        self.selectOutputPushButton.setObjectName("selectOutputPushButton")
        self.horizontalLayout.addWidget(self.selectOutputPushButton)
        self.outputLineEdit = QtWidgets.QLineEdit(parent=KnownMorphsExporterDialog)
        self.outputLineEdit.setObjectName("outputLineEdit")
        self.horizontalLayout.addWidget(self.outputLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(3, 10, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=KnownMorphsExporterDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.knownIntervalSpinBox = QtWidgets.QSpinBox(parent=KnownMorphsExporterDialog)
        self.knownIntervalSpinBox.setObjectName("knownIntervalSpinBox")
        self.horizontalLayout_2.addWidget(self.knownIntervalSpinBox, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label = QtWidgets.QLabel(parent=KnownMorphsExporterDialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 33, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.exportKnownMorphsPushButton = QtWidgets.QPushButton(parent=KnownMorphsExporterDialog)
        self.exportKnownMorphsPushButton.setObjectName("exportKnownMorphsPushButton")
        self.horizontalLayout_3.addWidget(self.exportKnownMorphsPushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(KnownMorphsExporterDialog)
        QtCore.QMetaObject.connectSlotsByName(KnownMorphsExporterDialog)

    def retranslateUi(self, KnownMorphsExporterDialog):
        _translate = QtCore.QCoreApplication.translate
        KnownMorphsExporterDialog.setWindowTitle(_translate("KnownMorphsExporterDialog", "Known Morphs Exporter"))
        self.selectOutputPushButton.setText(_translate("KnownMorphsExporterDialog", "Select Output"))
        self.label_2.setText(_translate("KnownMorphsExporterDialog", "Morphs with interval "))
        self.label.setText(_translate("KnownMorphsExporterDialog", "days or higher"))
        self.exportKnownMorphsPushButton.setText(_translate("KnownMorphsExporterDialog", "Export Known Morphs"))
