# Form implementation generated from reading ui file 'ankimorphs/ui/spacy_manager_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SpacyManagerDialog(object):
    def setupUi(self, SpacyManagerDialog):
        SpacyManagerDialog.setObjectName("SpacyManagerDialog")
        SpacyManagerDialog.resize(556, 573)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(SpacyManagerDialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spacyInstallPushButton = QtWidgets.QPushButton(parent=SpacyManagerDialog)
        self.spacyInstallPushButton.setObjectName("spacyInstallPushButton")
        self.horizontalLayout.addWidget(self.spacyInstallPushButton)
        self.spacyInstallationStatusLabel = QtWidgets.QLabel(parent=SpacyManagerDialog)
        font = QtGui.QFont()
        font.setItalic(True)
        self.spacyInstallationStatusLabel.setFont(font)
        self.spacyInstallationStatusLabel.setObjectName("spacyInstallationStatusLabel")
        self.horizontalLayout.addWidget(self.spacyInstallationStatusLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.languagesListWidget = QtWidgets.QListWidget(parent=SpacyManagerDialog)
        self.languagesListWidget.setObjectName("languagesListWidget")
        self.horizontalLayout_2.addWidget(self.languagesListWidget)
        self.modelsListWidget = QtWidgets.QListWidget(parent=SpacyManagerDialog)
        self.modelsListWidget.setObjectName("modelsListWidget")
        self.horizontalLayout_2.addWidget(self.modelsListWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.installModelPushButton = QtWidgets.QPushButton(parent=SpacyManagerDialog)
        self.installModelPushButton.setObjectName("installModelPushButton")
        self.verticalLayout.addWidget(self.installModelPushButton)
        self.deleteModelPushButton = QtWidgets.QPushButton(parent=SpacyManagerDialog)
        self.deleteModelPushButton.setObjectName("deleteModelPushButton")
        self.verticalLayout.addWidget(self.deleteModelPushButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.purgeSpacyPushButton = QtWidgets.QPushButton(parent=SpacyManagerDialog)
        self.purgeSpacyPushButton.setObjectName("purgeSpacyPushButton")
        self.verticalLayout.addWidget(self.purgeSpacyPushButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(SpacyManagerDialog)
        QtCore.QMetaObject.connectSlotsByName(SpacyManagerDialog)

    def retranslateUi(self, SpacyManagerDialog):
        _translate = QtCore.QCoreApplication.translate
        SpacyManagerDialog.setWindowTitle(_translate("SpacyManagerDialog", "spaCy Manager"))
        self.spacyInstallPushButton.setText(_translate("SpacyManagerDialog", "Install spaCy"))
        self.spacyInstallationStatusLabel.setText(_translate("SpacyManagerDialog", "spaCy is not installed. Please install it to continue."))
        self.installModelPushButton.setText(_translate("SpacyManagerDialog", "Install Model"))
        self.deleteModelPushButton.setText(_translate("SpacyManagerDialog", "Delete Model"))
        self.purgeSpacyPushButton.setText(_translate("SpacyManagerDialog", "Purge spaCy"))
