# Form implementation generated from reading ui file 'ankimorphs/ui/tag_selection.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TagSelectionDialog:
    def setupUi(self, TagSelectionDialog):
        TagSelectionDialog.setObjectName("TagSelectionDialog")
        TagSelectionDialog.resize(593, 451)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(TagSelectionDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setContentsMargins(-1, -1, -1, 12)
        self.searchLayout.setObjectName("searchLayout")
        self.label = QtWidgets.QLabel(parent=TagSelectionDialog)
        self.label.setObjectName("label")
        self.searchLayout.addWidget(self.label)
        self.searchLineEdit = QtWidgets.QLineEdit(parent=TagSelectionDialog)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.searchLayout.addWidget(self.searchLineEdit)
        self.verticalLayout_2.addLayout(self.searchLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=TagSelectionDialog)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.buttonLayout = QtWidgets.QVBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.unselectAllButton = QtWidgets.QPushButton(parent=TagSelectionDialog)
        self.unselectAllButton.setStyleSheet("")
        self.unselectAllButton.setObjectName("unselectAllButton")
        self.buttonLayout.addWidget(self.unselectAllButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.buttonLayout.addItem(spacerItem)
        self.viewAllTagsPushButton = QtWidgets.QPushButton(parent=TagSelectionDialog)
        self.viewAllTagsPushButton.setObjectName("viewAllTagsPushButton")
        self.buttonLayout.addWidget(self.viewAllTagsPushButton)
        self.viewSelectedTagsPushButton = QtWidgets.QPushButton(parent=TagSelectionDialog)
        self.viewSelectedTagsPushButton.setObjectName("viewSelectedTagsPushButton")
        self.buttonLayout.addWidget(self.viewSelectedTagsPushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.buttonLayout.addItem(spacerItem1)
        self.applyButton = QtWidgets.QPushButton(parent=TagSelectionDialog)
        self.applyButton.setObjectName("applyButton")
        self.buttonLayout.addWidget(self.applyButton)
        self.horizontalLayout.addLayout(self.buttonLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(TagSelectionDialog)
        QtCore.QMetaObject.connectSlotsByName(TagSelectionDialog)

    def retranslateUi(self, TagSelectionDialog):
        _translate = QtCore.QCoreApplication.translate
        TagSelectionDialog.setWindowTitle(_translate("TagSelectionDialog", "Tag Selector"))
        self.label.setText(_translate("TagSelectionDialog", "Search:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TagSelectionDialog", "Exclude"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TagSelectionDialog", "Include"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TagSelectionDialog", "Tag"))
        self.unselectAllButton.setText(_translate("TagSelectionDialog", "Unselect All"))
        self.viewAllTagsPushButton.setText(_translate("TagSelectionDialog", "View All Tags"))
        self.viewSelectedTagsPushButton.setText(_translate("TagSelectionDialog", "View Selected Tags"))
        self.applyButton.setText(_translate("TagSelectionDialog", " Apply"))
