# Form implementation generated from reading ui file 'ankimorphs/ui/view_morphs_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ViewMorphsDialog(object):
    def setupUi(self, ViewMorphsDialog):
        ViewMorphsDialog.setObjectName("ViewMorphsDialog")
        ViewMorphsDialog.resize(276, 257)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ViewMorphsDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=ViewMorphsDialog)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(ViewMorphsDialog)
        QtCore.QMetaObject.connectSlotsByName(ViewMorphsDialog)

    def retranslateUi(self, ViewMorphsDialog):
        _translate = QtCore.QCoreApplication.translate
        ViewMorphsDialog.setWindowTitle(_translate("ViewMorphsDialog", "View Morphemes"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ViewMorphsDialog", "Inflection"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ViewMorphsDialog", "Lemma"))
