name: Lint and Test

on: [push, pull_request]

jobs:
  build:
    permissions:
      actions: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python_version: ['3.9']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: tlambert03/setup-qt-libs@19e4ef2d781d81f5f067182e228b54ec90d23b76  # installs libraries necessary to run a Qt desktop environment on linux runners
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version:  ${{ matrix.python_version }}
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip virtualenv
        python -m virtualenv pyenv
        if [ "${{ runner.os }}" = "Windows" ]; then
          source pyenv/Scripts/activate
        else
          source pyenv/bin/activate
        fi
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Lint & Test
      shell: bash
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          source pyenv/Scripts/activate
        else
          source pyenv/bin/activate
        fi
        pre-commit run --all-files