name: Caching

on:
  workflow_dispatch:
    inputs:
      name:
        description: "What needs updating?"

jobs:
  build:
    permissions:
      actions: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        persist-credentials: false
    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt