name: 'Lock Threads'

on:
  schedule:
    - cron: '21 2 * * *'
  workflow_dispatch:

concurrency:
  group: lock-threads

jobs:
  action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: dessant/lock-threads@1bf7ec25051fe7c00bdd17e6a7cf3d7bfb7dc771 # v5.1
        with:
          issue-inactive-days: '7'
          issue-comment: >
            This issue has been automatically locked since there
            has not been any recent activity after it was closed.
            Please open a new issue for related bugs.
          issue-lock-reason: 'resolved'
          process-only: 'issues'
          log-output: true